"use client";

import { useMemo, useState } from "react";
import {
  ArrowRight, BarChart3, Building2, Check, ChevronDown, Database,
  FileText, Gauge, Layers3, ListTodo, Mail, Menu, Search, ShieldCheck,
  Sparkles, Target, Users, X
} from "lucide-react";

const services = ["Website", "SEO", "Ads", "Social", "Chatbot", "Automation"];
const opportunityMap: Record<string, [string,string,string]> = {
  Website:["Mobile booking friction detected","Reduce the steps between visit and booking","Website Design"],
  SEO:["Weak local search visibility","Capture more high-intent local demand","SEO Services"],
  Ads:["Paid acquisition gap","Create a measurable path from click to conversion","Google Ads / PPC"],
  Social:["Inconsistent social presence","Turn an underused channel into a demand asset","Social Media"],
  Chatbot:["No instant conversational capture","Convert more visitors before they leave","AI Chatbot"],
  Automation:["Manual workflow handoffs","Reduce repetitive work and speed response","AI & Automation"],
};

const faqs = [
  ["How is LeadSaaS different from a lead scraper?","A scraper gives you contact records. LeadSaaS is designed to keep the opportunity context attached: why a prospect may be relevant, what evidence was found, what service may fit, and how that context can move into outreach."],
  ["What is the difference between Individual and Company?","Individual is prospect-oriented. Company is account-oriented and can add account qualification such as entity type, employee size, revenue context and company-specific contact requirements."],
  ["Can I review AI-generated outreach before sending?","Yes. The workflow supports generated drafts, review, editing and approval before queue execution."],
  ["Can I use my own sender accounts?","The Communication Hub supports user-configured Google, Microsoft and Custom SMTP sender accounts, with capacity and sender-rotation controls."],
  ["Does LeadSaaS send through LinkedIn or Instagram?","Native outreach currently centers on email. Verified contact data for other channels can be exported for use in the dedicated channel tool."],
  ["What happens after a prospect replies?","Replies can be surfaced for review, and you can create follow-up tasks with priorities and due dates to keep the opportunity moving."],
];

function Title({eyebrow,title,copy,center=false}:{eyebrow:string,title:string,copy:string,center?:boolean}){
  return <div className={center?"mx-auto max-w-3xl text-center":"max-w-3xl"}>
    <div className="eyebrow">{eyebrow}</div><h2 className="section-title">{title}</h2><p className="section-copy">{copy}</p>
  </div>
}

export default function Home(){
  const [mobile,setMobile]=useState(false);
  const [track,setTrack]=useState<"individual"|"company">("company");
  const [service,setService]=useState("Website");
  const [openFaq,setOpenFaq]=useState(0);
  const [signal,angle,offer]=useMemo(()=>opportunityMap[service],[service]);

  return <main className="min-h-screen bg-[#f7f9fc] text-slate-950">
    <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl">
      <div className="shell flex h-[72px] items-center justify-between">
        <a href="#" className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#173f80] text-sm font-black text-white">LS</div><div><div className="font-black">LeadSaaS</div><div className="text-[10px] font-bold uppercase tracking-[.17em] text-slate-400">Opportunity Intelligence</div></div></a>
        <nav className="hidden items-center gap-7 lg:flex"><a className="nav-link" href="#product">Product</a><a className="nav-link" href="#how">How it works</a><a className="nav-link" href="#tracks">Individual</a><a className="nav-link" href="#tracks">Company</a><a className="nav-link" href="#pricing">Pricing</a><a className="nav-link" href="#faq">Resources</a></nav>
        <div className="hidden items-center gap-3 lg:flex"><button className="btn-ghost">Sign in</button><button className="btn-primary">Start free <ArrowRight size={16}/></button></div>
        <button className="lg:hidden" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button>
      </div>
      {mobile&&<div className="border-t bg-white p-5 lg:hidden"><div className="grid gap-4 font-bold"><a href="#product">Product</a><a href="#how">How it works</a><a href="#tracks">Individual / Company</a><a href="#pricing">Pricing</a></div></div>}
    </header>

    <section className="relative overflow-hidden bg-white"><div className="hero-grid absolute inset-0 opacity-60"/><div className="shell relative grid min-h-[780px] items-center gap-14 py-20 lg:grid-cols-[.92fr_1.08fr]">
      <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-2 text-xs font-extrabold text-[#2457a8]"><Sparkles size={14}/> Stop collecting lists. Start discovering opportunities.</div><h1 className="hero-title">Find businesses with a <span className="text-[#1d58b7]">reason</span> to need what you sell.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600">LeadSaaS helps service businesses discover relevant prospects and company accounts, understand the opportunity behind them, and turn that intelligence into controlled, personalized outreach.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button className="btn-primary h-12 px-6">Start finding opportunities <ArrowRight size={17}/></button><a href="#how" className="btn-secondary h-12 px-6">See how it works</a></div><div className="mt-8 flex flex-wrap gap-3"><span className="pill"><ShieldCheck size={14}/> Evidence-led</span><span className="pill"><Users size={14}/> Individual + Company</span><span className="pill"><Mail size={14}/> Controlled email outreach</span></div></div>
      <div className="rounded-[30px] border border-slate-200 bg-[#0e1930] p-3 shadow-soft"><div className="rounded-[23px] bg-[#f8fafc] p-5"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black tracking-[.16em] text-[#2c67c6]">AI DISCOVERY</div><div className="mt-1 text-lg font-black">Opportunity Search</div></div><div className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-extrabold text-emerald-700">Ready</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="ui-field"><span>Market</span><strong>Miami, Florida</strong></div><div className="ui-field"><span>Business type</span><strong>Restaurants</strong></div></div><div className="mt-4 flex flex-wrap gap-2">{services.map(s=><button onClick={()=>setService(s)} key={s} className={`rounded-xl border px-3 py-2 text-xs font-extrabold ${service===s?"border-[#2558a9] bg-[#1c4f9f] text-white":"border-slate-200 bg-white text-slate-600"}`}>{s}</button>)}</div><div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-4"><div className="flex justify-between"><div><div className="text-[10px] font-black tracking-[.14em] text-[#2f64bb]">OPPORTUNITY FOUND</div><div className="mt-1 font-black">Bella&apos;s Italian Kitchen</div></div><div className="rounded-full bg-[#0f6d4b] px-3 py-1 text-xs font-black text-white">HOT · 87</div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="mini-card"><span>Verified signal</span><strong>{signal}</strong></div><div className="mini-card"><span>Sales angle</span><strong>{angle}</strong></div><div className="mini-card"><span>Offer</span><strong>{offer}</strong></div></div></div><div className="mt-4 flex items-center justify-between rounded-2xl border bg-white p-4"><div><div className="text-xs text-slate-500">Recommended first channel</div><div className="font-extrabold">Email · Verified contact</div></div><button className="rounded-xl bg-slate-950 px-4 py-2 text-xs font-extrabold text-white">Generate outreach</button></div></div></div>
    </div></section>

    <section id="product" className="section bg-white"><div className="shell"><Title center eyebrow="THE DIFFERENCE" title="A lead is more useful when you know why it matters." copy="Traditional lead tools stop at contact data. LeadSaaS is designed to keep the commercial context attached to the opportunity."/><div className="mt-12 grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] border bg-slate-50 p-7"><div className="mb-5 text-xs font-black tracking-[.14em] text-slate-400">THE OLD WAY</div>{["Search businesses","Scrape contacts","Export CSV","Guess who needs your service","Send generic messages","Lose context"].map(x=><div className="line-item text-slate-500" key={x}><X size={16}/> {x}</div>)}</div><div className="rounded-[28px] border border-blue-200 bg-[#f5f9ff] p-7 shadow-card"><div className="mb-5 text-xs font-black tracking-[.14em] text-[#2b63bc]">LEADSAAS</div>{["Define what you sell","Discover relevant opportunities","Understand why they matter","Preserve the evidence","Build the right sales angle","Track engagement and follow up"].map(x=><div className="line-item font-bold" key={x}><Check size={16} className="text-emerald-600"/> {x}</div>)}</div></div></div></section>

    <section id="tracks" className="section bg-[#0f1b31] text-white"><div className="shell"><Title center eyebrow="TWO OPERATING TRACKS" title="One platform. Two focused ways to develop opportunities." copy="Choose the context that matches how you sell: prospect-oriented Individual work or account-oriented Company development."/><div className="mx-auto mt-9 flex w-fit rounded-2xl border border-white/10 bg-white/5 p-1"><button onClick={()=>setTrack("individual")} className={`track-toggle ${track==="individual"?"active":""}`}><Users size={17}/> Individual</button><button onClick={()=>setTrack("company")} className={`track-toggle ${track==="company"?"active":""}`}><Building2 size={17}/> Company</button></div><div className="mt-9 grid gap-6 lg:grid-cols-2"><div className="rounded-[28px] border border-white/10 bg-white/[.06] p-7"><div className="text-xs font-black tracking-[.16em] text-blue-300">{track==="company"?"ACCOUNT WORKSPACE":"INDIVIDUAL WORKSPACE"}</div><h3 className="mt-3 text-3xl font-black">{track==="company"?"Develop company accounts, not just contact records.":"Work prospect-level opportunities without mixing account workflows."}</h3><p className="mt-4 leading-7 text-slate-300">{track==="company"?"Company Search can add account qualification, company context and decision-maker contact requirements before outreach.":"Individual keeps owner-led, professional and local-market opportunities organized around the prospect as the primary record."}</p></div><div className="rounded-[28px] bg-white p-6 text-slate-950"><div className="grid gap-4 md:grid-cols-3">{(track==="company"?[["Entity type","HQ · Branch · Parent · Subsidiary",Building2],["Account profile","Employees · Revenue context",Gauge],["Contact context","General · Founder · Decision-maker",Users]]:[["Target","Owners · Professionals · Local businesses",Users],["Opportunity","Service-aware discovery",Target],["Workflow","Prospect context kept separate",Layers3]]).map(([a,b,Icon]:any)=><div key={a} className="rounded-2xl border bg-slate-50 p-5"><Icon size={20} className="text-[#2157aa]"/><div className="mt-5 text-sm font-black">{a}</div><div className="mt-2 text-sm leading-6 text-slate-500">{b}</div></div>)}</div></div></div></div></section>

    <section id="how" className="section bg-white"><div className="shell"><Title center eyebrow="HOW IT WORKS" title="From ‘who can I contact?’ to ‘what should I do next?’" copy="LeadSaaS connects discovery, intelligence, outreach and follow-up into one coherent operating flow."/><div className="mt-14 grid gap-4 md:grid-cols-2 xl:grid-cols-6">{[["01","Define","Choose market and service.",Search],["02","Discover","Find relevant opportunities.",Target],["03","Understand","Review evidence and fit.",Sparkles],["04","Strategize","Turn evidence into an angle.",Layers3],["05","Engage","Generate, review and send.",Mail],["06","Follow up","Track replies and next actions.",ListTodo]].map(([n,t,c,Icon]:any)=><div className="process-card" key={n}><div className="flex justify-between"><span className="text-xs font-black text-[#2b63bc]">{n}</span><Icon size={18} className="text-slate-400"/></div><div className="mt-8 font-black">{t}</div><p className="mt-2 text-sm leading-6 text-slate-500">{c}</p></div>)}</div></div></section>

    <section className="section bg-[#f2f6fb]"><div className="shell grid gap-12 lg:grid-cols-2 lg:items-center"><Title eyebrow="EVIDENCE → OUTREACH" title="Understand first. Write second." copy="The strongest outreach starts with a reason. LeadSaaS connects verified facts, detected problems and strategy context to the sales angle before the final message."/><div className="rounded-[30px] border bg-white p-5 shadow-soft"><div className="grid gap-4 sm:grid-cols-2"><div className="logic-card"><span>VERIFIED FACT</span><strong>Mobile booking flow requires multiple steps</strong></div><div className="logic-card"><span>DETECTED PROBLEM</span><strong>Potential conversion friction</strong></div><div className="logic-card"><span>STRATEGY INFERENCE</span><strong>Reduce friction before abandonment</strong></div><div className="logic-card border-blue-200 bg-blue-50"><span>RECOMMENDED ANGLE</span><strong>Make booking faster for mobile visitors</strong></div></div><div className="mt-4 rounded-2xl bg-[#101a2f] p-5 text-white"><div className="text-[10px] font-black tracking-[.15em] text-blue-300">AI-ASSISTED DRAFT</div><div className="mt-4 text-sm font-bold">Subject: A simpler booking path for Bella&apos;s</div><p className="mt-3 text-sm leading-6 text-slate-300">I noticed the mobile booking path asks visitors to move through several steps before confirming...</p></div></div></div></section>

    <section className="section bg-white"><div className="shell"><Title center eyebrow="CONTINUITY" title="Keep the ‘why’ attached to every opportunity." copy="Qualified discoveries can move into prospects, campaigns and CRM views without becoming anonymous rows in a disconnected list."/><div className="mt-12 grid gap-5 lg:grid-cols-3">{[["Prospects","Keep selected opportunities organized and deduplicated while preserving campaign associations.",Users],["Campaigns","Preserve the selected group, service intent, evidence context and outreach lifecycle.",Layers3],["CRM control","See whether work is preparing, ready, active or completed—and what happens next.",BarChart3]].map(([t,c,Icon]:any)=><div className="feature-card" key={t}><div className="icon-box"><Icon size={20}/></div><h3>{t}</h3><p>{c}</p></div>)}</div></div></section>

    <section className="section bg-[#0f1b31] text-white"><div className="shell grid gap-12 lg:grid-cols-2 lg:items-center"><div><Title eyebrow="CONTROLLED EXECUTION" title="Use your own sender infrastructure without treating capacity as unlimited." copy="Configure sender accounts, monitor readiness and use capacity-aware rotation before approved outreach enters the queue."/><div className="mt-8 flex flex-wrap gap-3"><span className="pill">Google / Gmail</span><span className="pill">Microsoft / Outlook</span><span className="pill">Custom SMTP</span></div></div><div className="rounded-[28px] border border-white/10 bg-white/[.06] p-6">{[["Agency Sender 01","Healthy","34 / 50"],["Agency Sender 02","Healthy","21 / 50"],["Agency Sender 03","Warming","12 / 30"]].map(([a,b,c])=><div key={a} className="mb-3 rounded-2xl border border-white/10 bg-white/[.05] p-4"><div className="flex justify-between"><div><div className="font-bold">{a}</div><div className="mt-1 text-xs text-emerald-300">{b}</div></div><div className="text-sm font-bold text-slate-300">{c}</div></div></div>)}<div className="mt-4 flex justify-between rounded-2xl bg-blue-500/10 p-4 text-sm"><span>Rotation</span><strong>Adaptive capacity</strong></div></div></div></section>

    <section className="section bg-white"><div className="shell"><Title center eyebrow="WHAT HAPPENS NEXT" title="Know what happens after you hit send." copy="Follow the outreach lifecycle without turning the product into a wall of disconnected analytics."/><div className="mx-auto mt-12 max-w-5xl rounded-[30px] border bg-[#f8fafc] p-6 shadow-card"><div className="grid gap-3 md:grid-cols-5">{[["Sent","184"],["Delivered","171"],["Opened","86"],["Replied","24"],["Closed","7"]].map(([a,b])=><div key={a} className="rounded-2xl bg-white p-5"><div className="text-xs font-bold text-slate-400">{a}</div><div className="mt-2 text-2xl font-black">{b}</div></div>)}</div></div></div></section>

    <section className="section bg-[#f2f6fb]"><div className="shell grid gap-10 lg:grid-cols-2 lg:items-center"><Title eyebrow="FOLLOW-UP" title="Keep opportunities moving after the first response." copy="Turn a promising opportunity or reply into a concrete next action with a due date, priority and visible completion history."/><div className="rounded-[28px] border bg-white p-6 shadow-card">{[["Send revised proposal","Acme Corp","High"],["Follow up on SEO audit","Bella's Kitchen","Medium"],["Confirm next-step call","Northstar Dental","Low"]].map(([a,b,c])=><div className="flex items-start gap-4 border-b py-4 last:border-0" key={a}><div className="mt-1 h-5 w-5 rounded-full border-2 border-slate-300"/><div className="flex-1"><div className="font-extrabold">{a}</div><div className="mt-1 text-sm text-slate-500">{b}</div></div><div className="text-xs font-black text-slate-500">{c}</div></div>)}</div></div></section>

    <section className="section bg-white"><div className="shell"><Title center eyebrow="MORE OF THE OPERATING SYSTEM" title="Supporting capabilities, without the feature-wall." copy="The platform includes the working surfaces needed to keep opportunity development organized from search through follow-up."/><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Reusable templates",FileText],["Campaign workspaces",Layers3],["Prospect organization",Users],["CSV export",Database],["Communication Hub",Mail],["Overview analytics",BarChart3],["Tasks & follow-ups",ListTodo],["CRM control surface",Gauge]].map(([x,Icon]:any)=><div key={x} className="compact-card"><Icon size={19} className="text-[#2458a7]"/><span>{x}</span></div>)}</div></div></section>

    <section id="pricing" className="section bg-[#f2f6fb]"><div className="shell"><Title center eyebrow="PRICING" title="A pricing section ready for your real plans." copy="No invented prices. Insert final plan names, limits and commercial terms when they are locked."/><div className="mt-12 grid gap-5 lg:grid-cols-3">{["Starter","Growth","Business"].map((name,i)=><div key={name} className={`pricing-card ${i===1?"featured":""}`}><h3 className="text-2xl font-black">{name}</h3><div className="mt-3 text-sm text-slate-500">Final pricing to be inserted</div><div className="my-6 h-px bg-slate-200"/>{["Opportunity discovery","Individual + Company workflows","Campaign organization","Outreach controls"].map(x=><div key={x} className="mb-3 flex items-center gap-2 text-sm font-semibold"><Check size={16} className="text-emerald-600"/> {x}</div>)}<button className={i===1?"btn-primary mt-5 w-full justify-center":"btn-secondary mt-5 w-full justify-center"}>Choose plan</button></div>)}</div></div></section>

    <section id="faq" className="section bg-white"><div className="shell grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><Title eyebrow="FAQ" title="The questions that matter before you trust the workflow." copy="Clear answers without claiming features the product does not support."/><div className="rounded-[28px] border bg-white p-2 shadow-card">{faqs.map(([q,a],i)=><div key={q} className="border-b last:border-0"><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} className="flex w-full items-center justify-between gap-4 px-5 py-5 text-left font-extrabold">{q}<ChevronDown size={18}/></button>{openFaq===i&&<p className="px-5 pb-5 text-sm leading-7 text-slate-600">{a}</p>}</div>)}</div></div></section>

    <section className="bg-[#173f80] py-20 text-white"><div className="shell text-center"><div className="mx-auto max-w-4xl"><div className="text-xs font-black tracking-[.2em] text-blue-200">FROM MARKET TO NEXT ACTION</div><h2 className="mt-4 text-4xl font-black tracking-[-.04em] sm:text-5xl">Don&apos;t just find people to contact. Find a reason to start the conversation.</h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-blue-100">Define what you sell, discover where it may be needed, understand the opportunity, and keep the context connected through outreach and follow-up.</p><div className="mt-8"><button className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-white px-6 text-sm font-black text-[#173f80]">Start finding opportunities <ArrowRight size={17}/></button></div></div></div></section>

    <footer className="bg-[#0c1527] py-14 text-slate-300"><div className="shell"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-6"><div className="lg:col-span-2"><div className="flex items-center gap-3 text-white"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-white text-sm font-black text-[#173f80]">LS</div><div className="font-black">LeadSaaS</div></div><p className="mt-4 max-w-sm text-sm leading-6 text-slate-400">Opportunity intelligence and outreach operations for service providers that want more context than a raw contact list.</p></div>{[["Product",["Opportunity Discovery","Opportunity Intelligence","Outreach","Campaigns"]],["Workspaces",["Individual","Company","Communication Hub","CRM"]],["Resources",["How it works","FAQ","Contact","About"]],["Programs",["Affiliate Program","Partner Program","Pricing","Sign in"]]].map(([t,links]:any)=><div key={t}><div className="mb-4 text-sm font-black text-white">{t}</div><div className="space-y-3 text-sm text-slate-400">{links.map((x:string)=><a href="#" key={x} className="block">{x}</a>)}</div></div>)}</div><div className="mt-12 flex flex-col gap-4 border-t border-white/10 pt-7 text-xs text-slate-500 md:flex-row md:justify-between"><div>© 2026 LeadSaaS. All rights reserved.</div><div className="flex gap-5"><a href="#">Privacy Policy</a><a href="#">Terms of Service</a><a href="#">Cookies Policy</a></div></div></div></footer>
  </main>
}
